# Generated by Django 4.2.7 on 2023-11-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_managers_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Post'},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title', 'slug'], name='posts_post_title_654bed_idx'),
        ),
    ]
