# Generated by Django 4.2.7 on 2023-11-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.CharField(choices=[(None, 'Empty'), ('d', 'Draft'), ('p', 'Publish')], default='d', max_length=2),
        ),
    ]
